#A sample calculator
a1=input("enter a value:")
a=int(a1)
b1=input("enter b value:")
b=int(b1)
print("the sum is:",(a+b))
print(" the sub is:",(a-b))
print("the multipication is:",(a*b))
print("the division is:",(a/b))
print("the reminder is:",(a%b))
print("the power is:",(a**b))